---
services:
  - type: web
    plan: free
    name: starter-kit
    region: frankfurt
    env: node
    buildCommand: npm ci --include dev; npm run build; npm --workspace api prune --omit dev
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: LOG_LEVEL
        value: info
      - key: NODE_ENV
        value: production
