name: Keep dependencies up-to-date

on:
  schedule:
    - cron: "0 0 * * SUN"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GH_DEPLOY_KEY }}
      - uses: textbook/take-action@nodejs
        with:
          checkout: "false"
          node-version: 20
      - run: |
          git config --global user.name "gh-actions"
          git config --global user.email "actions@github.com"
      - run: ./bin/up-to-date.sh
