---
name: Keep Render deployment alive

on:
  schedule:
    - cron: "14 3 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: curl 'https://starter-kit-v2.onrender.com/api/message'
