name: CI

on:
  push:
    branches: [ v2 ]

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: textbook/take-action@nodejs
      - run: npmx playwright install --with-deps
      - run: npm run lint
      - run: npm test
      - run: npm run e2e
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          push: false
