name: CI

on:
  push:
    branches: [ v2 ]

jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - uses: textbook/take-action@nodejs
        with:
          node-version: 20
      - run: npx playwright install --with-deps
      - run: npm run lint
      - run: npm test
      - run: npm run e2e
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: textbook/take-action@nodejs
        with:
          node-version: 20
      - run: npx playwright install --with-deps
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          load: true
          push: false
          tags: textbook/starter-kit:v2
      - id: docker-run
        run: |
          echo "id=$(docker run \
            --detach \
            --env LOG_LEVEL=debug \
            --env NODE_ENV=docker \
            --init \
            --publish 80:4321 \
            textbook/starter-kit:v2)" >> $GITHUB_OUTPUT
      - run: npm run e2e
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:4321
      - if: always()
        run: docker logs ${{ steps.docker-run.outputs.id }}
